kalbasit/shabka

home.nix
modules/home-manager/lowbatt/default.nix

The lowbatt service monitors the battery and notifies the user if the battery is at or below 10% and will hibernate the laptop if the battery is at or below 5%.

home: add lowbatt module and enable the service

---

hosts/cratos/home.nix
hosts/hades/home.nix
hosts/zeus/home.nix
modules/home/generic/nixos.nix
modules/home/workstation/i3/default.nix
modules/home/workstation/i3/i3-config.lib.nix
modules/nixos/general/home-manager.nix
modules/nixos/general/users.nix
modules/nixos/software/zsh.nix

This commit moves away from setting the `home-manager.users.<name>` directly from the `hosts/<host>/home.nix` into setting it on a new NixOS option. The new option is set to a function, given the user and nixosConfig, returns a new function to be set directly on `home-manager.users.<name>`. This way, I can dynamically create users as I need and configure the home of these users using the same function.

nixos: dynamically create users; generate their HM config through a function call

---

hosts/zeus/configuration.nix
hosts/zeus/win10.xml

My entire NS network is geared towards NS1 being the primary network
interface. For instance, apollo.nasreddine.com resolves to NS1 address
that is not accessible from NS2 so I cannot use NS2 for the network
access!

Swap win10 network interfaces

---

modules/nixos/general/version.nix

When the nixpkgs is pinned using `builtins.fetchGit` instead of a
channel, NixOS lose track of the commit because the fetcher removes the
`.git` folder. This changeset constructs the nixos-version back using
the `system.nixos.release` stitched with the first seven characters of
the revision in the JSON file describing the nixpkgs source.
closes #87

nixos: fix the nixos-version broken by the nixpkgs pinning

---

external/home-manager-version.json
external/home-manager.nix
modules/home/generic/non-nixos.nix
modules/nixos/general/users.nix

rycee/home-manager#529 is now merged and the patch is no longer needed.

external/home-manager: update to c48fd9d

---

external/nixpkgs-unstable-version.json

This partially reverts commit 7b8c42422a14dbc87731dfc4236c6eaf0abb2e0b.
closes #98

external/nixpkgs-unstable: revert back to 44b02b

---

.circleci/config.yml
external/0001-pam-u2f-refactor-docs-about-u2f_keys-path.patch
external/nixpkgs-stable.nix
modules/nixos/workstation/yubikey.nix
scripts/nixops.sh
scripts/nixos-rebuild.sh

This change patches nixpkgs stable with https://github.com/NixOS/nixpkgs/pull/54756 and enables `u2f.cue`.

nixos: apply U2F improvement patch and enable u2f.cue

---

external/nixos-hardware.nix
hosts/cratos/configuration.nix
hosts/hades/configuration.nix
hosts/hera/configuration.nix
hosts/zeus/configuration.nix
modules/nixos/hardware/xps-13.nix

I was getting black screens and random lockups when using the XPS 9370 profile. It turned out to be due to the changes specific to Kaby Lake that are being imported. This CPU is actually Whiskey Lake. The profile also disables a bug fix that is not present on this model.
See https://github.com/NixOS/nixos-hardware/pull/97
fixes #138

hosts/cratos: use the xps-9380 nixos hardware profile

---

modules/neovim/init.vim

[Better Whitespace](https://github.com/ntpeters/vim-better-whitespace)
has been updated upstream to no longer require the BufEnter command, but
it's also now asking for confirmation when trimming white spaces on save
by default. I don't desire to confirm on every save, I will disable it
with `:DisableStripWhitespaceOnSave` if I'm editing a file and would
like to conserve them.

[NeoVim] Update the use of BetterWhitespace plugin

---

external/home-manager-version.json
modules/nixos/general/home-manager.nix

Switch home manager to https://github.com/rycee/home-manager/pull/580 in order to install user packages through NixOS's user packages. This allows me to build VM that are able to have user packages.

external/home-manager: Install packages through NixOS users.users.<name?>.packages

---

modules/nixos/general/editor.nix

In #159 the user packages are now installed through NixOS at `/etc/profiles/per-user/<per-user>/bin` which comes second after `/run/current-system/sw/bin` in the PATH so we cannot have `neovim` installed on the system. Use `mine.neovim.enable` coming from #142 to install it system-wide.

nixos: do not install neovim, it shadows user's version

---

external/kalbasit-nur-version.json
modules/home/software/zsh/default.nix
modules/home/software/zsh/init-extra.zsh

[Shell] Replace exa with ls/LS_COLORS

---

.circleci/config.yml
modules/home/software/packages.nix
modules/home/software/zsh/default.nix

When a CircleCI job has both the `macos` key and the `docker` key, it does
pick `docker` (preference or order, unsure!). That means that I have
been testing in a Linux docker container for the entire time! This change enables true Darwin job on CircleCI.

CircleCI: Fix the Darwin test

---

hosts/hades/release

GnuPG is not working correctly with YubiKey, I'm getting `No such device
again`. I believe it's the same issue as before where scdaemon attempts
to contact the Broadcom card even though I do have `reader-port Yubico
Yubikey` in `~/.gnupg/scdaemon.conf`.
This partially reverts commit 5dd31dbf801173ce347827ddb061e4914cb58e4c.

hosts/hades: revert back to the stable channel

---

external/home-manager-version.json
external/nixpkgs-stable-version.json
external/nixpkgs-unstable-version.json
external/nur-version.json
scripts/update-external.sh

In addition to the updated externals below, this change fixes an issue with the update script not operating correctly when adding a new external dependency.
- NUR: Compare changes at https://github.com/nix-community/NUR/compare/11937cf90187b7cb1eb43b02c8fc3a45cb16fd8b...6328222b3a68f575b53268888217c3c27125d0f8
- nixpkgs-unstable: Compare changes at https://github.com/NixOS/nixpkgs-channels/compare/929cc78363e6878e044556bd291382eab37bcbed...36f316007494c388df1fec434c1e658542e3c3cc
- nixpkgs-stable: Compare changes at https://github.com/NixOS/nixpkgs-channels/compare/5225d4bf0193b51cfb1a200faa4ae50958f98c62...9bd45dddf8171e2fd4288d684f4f70a2025ded19
- home-manager: Compare changes at https://github.com/rycee/home-manager/compare/79731e6ab4d41ce4569fe6b60623a590675288af...799a90ecfaa717bc617f …

[External] Fix a bug in the update script, update all external dependencies

---

modules/home/software/tmux.nix

The external dependencies were updated in 99922579fc5389e456ca2644dedd93dc53fa59e8, and home-manager received the new TMux update which added `escapeTime` defaulted to 500. This change sets `escapeTime` back to zero among other new settings.

[TMux] Update the configuration to work with latest HM

---

modules/home/software/zsh/default.nix

In d3b1abe39d94545c04e7003202abb98d8000a477 or 99922579fc5389e456ca2644dedd93dc53fa59e8 NeoVim started booting in a broken state after SWM starts it up a TMux session. It seems for some reason that it's breaking because it's starting too fast. This change sets `vim_ready` to `sleep 1` so NeoVim gets delayed a second after the TMux session has started.

[Home] Fix NeoVim starting in a bad graphic state

---

modules/neovim/init.vim

Deoplete and Multiple cursors seem to be in conflict, so this change disables deoplete before entering multiple cursors and it enables it after it's done.
fixes #85

[NeoVim] Disable deoplete before entering multiple cursors

---

modules/neovim/init.vim

When entering multiple cursors, check if deoplete is enabled before
attempting to disable it. When the multiple cursors mode is ending,
re-enable deoplete only if it was found enabled before.
fixes #85 
improves #178

[NeoVim] Improve the multiple cursor compatibility with deoplete

---

modules/neovim/init.vim

In addition to disabling automatic markdown folding, this change disables Polyglot Markdown support and an extraneous BufferEnter command for Markdown. It also enables alignment for Terraform files, this option is described as `Allow vim-terraform to override your .vimrc indentation syntax for matching files`.
Cleanup:
- Options for missing `Markdown Preview` plugins are now removed.
- Unused function `ShowRoutes` is now removed.
closes #186

[NeoVim] Disable automatic Markdown folding

---

modules/home/software/zsh/plugins/functions/register_u2f

Registering U2F devices are one line per U2F. The current version is not
adding a newline at the end of the entry, and in turns adding a new U2F
device gets appended to the entry of the previous U2F key effectively
breaking both keys.

[Shell] register_u2f: make sure there is a newline at the end

---

external/default.nix
external/iohk-nix/default.nix
external/iohk-nix/update.sh
external/iohk-nix/version.json
modules/nixos/general/version.nix

Use <iohk-nix>.commitIdFromGitRepo to correctly compute the Git revision of shabka from a Git worktree. Where <iohk-nix> is located at https://github.com/input-output-hk/iohk-nix.

[nixos] Set the NixOS label correctly set from within a Git worktree

---

hosts/athena/configuration.nix
hosts/cratos/configuration.nix
hosts/hades/configuration.nix
hosts/hera/configuration.nix
hosts/poseidon/configuration.nix

The absence of the secrets was causing `nix.buildMachines` to be set to `[ {} {} ]`. This value is invalid as each item in the list was missing the hostname.
This change also removes all build machines from my Darwin configurations because my build machines do not support Darwin and thus useless.
fixes #211

Fix nix.buildMachines on all hosts when my secrets are not present

---

modules/home/software/git/default.nix

Resolves the TODO in `modules/home/software/git/default.nix`

[Git] Make user's name, email and PGP key configurable

---

modules/home/software/tmux.nix

This change fixes the TMux configuration for new TMux 2.9. The format of the new styling is described in the [manual](https://man.openbsd.org/tmux.1#STYLES).
closes #217

[Tmux] Fix the styles for >= 2.9

---

modules/home/software/tmux.nix

TMux is currently broken on Darwin because of secureSocket. It returns an error: `error creating /run/user/$(id -u)/tmux-501`.

[home/TMux] enable secureSocket on Linux only

---

modules/home/software/tmux.nix

Set TERM to tmux-256color on Linux, and to xterm-256color on Darwin.
closes #228

[home/TMux] set a different TERM on Darwin than Linux

---

scripts/build-host.sh
scripts/diff-host.sh

A new script to show the differences in the build of a host against two revisions. Usage: `./scripts/diff-host.sh <host> <base-rev> [target-rev]`. All fields except `target-rev` is required, `target-rev` defaults to the `HEAD`.
```console
λ  ./scripts/diff-host.sh hades master
λ  ./scripts/diff-host.sh hades master my-feature-branch
```

scripts/diff-host.sh: diff a host against two revisions

---

external/nixpkgs/19.03/default.nix
external/nixpkgs/unstable/default.nix
modules/home/software/packages.nix
overlays/slack.nix

Without Slack installed, xdg-open cannot find the handler of slack://
and makes it difficult to login to a new team.

[home] install Slack not Slack CLI; switch to unstable Slack

---

modules/neovim/init.vim

Configure vim-go to use `gopls` as the language server when working with Go files. This requires the unstable release and is a noop on the 19.03 release.
closes #239

[NeoVim] Use gopls as the language server for Go

---

modules/home/software/ssh.nix

Set the default ssh configuration when no `privateSSHPath` is given to what is recommended by NixOS and other parties :
- https://nixos.org/nixos/options.html#services.openssh
- https://stribika.github.io/2015/01/04/secure-secure-shell.html
- https://infosec.mozilla.org/guidelines/openssh

home: ssh: hardening default configuration

---

modules/nixos/general/keyboard.nix

There was an unsupported option when setting the layout to bépo.

keyboard: fix configuration when using bépo

---

modules/home/services/gnupg.nix

Allows to configure the default cache TTL.

home: gnupg: extended config

---

external/nixpkgs/19.09/default.nix
external/nixpkgs/unstable/default.nix
external/nixpkgs/unstable/fix-nvim-terraform-plugin.patch

Vim keeps showing an error on startup, complaining about vim-terraform attempting to define action on an event that does not exist. This PR patches nixpkgs https://github.com/NixOS/nixpkgs/pull/76845 with which includes the fix filed upstream here: https://github.com/hashivim/vim-terraform/pull/133

external/nixpkgs: apply #76845 to fix vim-terraform

---

.circleci/config.yml
scripts/push-to-cachix.sh

Closes #285 
If accepted, the CI env variables `CACHIX_SIGNING_KEY` must be moved to `YL_CACHIX_SIGNING_KEY`, and `RISSON_CACHIX_SIGNING_KEY` must be added to allow for risson's hosts to be pushed to his cachix.

scripts/push-to-cachix: improvements (#285)

---

rfcs/0001-shabka-usage-design.md
rfcs/README.md

Closes #263.
Relevant issues: #246 #55 #281 
The goal is to design a system where `shabka` is just a tool like
`home-manager`, and relies on configuration files provided by the user.
The tools and ways to configure at the disposition of the user would be those:
* the command `shabka`, installed like `home-manager` which basically does the
stuff the user wants to do on a regular basis that we currently have in
`./scripts` ;
* a `dotshabka` like directory for the user's personal preferences settings and
default values for `shabka` options, or overriding stuff we define in
`shabka`. We will refer to this as `.shabka` ;
* a `dotshabka` like directory for the user's hosts. We will refer to this as
`.hosts`.

[RFC 0001] Shabka CLI design

---

modules/darwin/general/nix.nix
modules/nixos/general/nix.nix

By using caches over HTTP, it allows us to spawn up a local binary cache for bandwidth savings. Although HTTP does not prevent MITM attacks, all of the cached binaries are signed. If the signature does not match, nix will reject it and move on to the next cache.
Setting these values does not remove the default cache `https://cache.nixos.org`, but if it does not resolve (like in the case of local cache) it will get ignored.
Leaving the command to use on my local network to switch existing hosts as HTTPS no longer resolves:
```
sudo --preserve-env=DOTSHABKA_PATH ./bin/shabka boot --option binary-caches 'http://cache.nixos.org http://yl.cachix.org http://risson.cachix.org' --option trusted-public-keys 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= …
```

nixos/darwin: switch to using binary cache over HTTP

---

modules/home/workstation/i3/bar/polybar.lib.nix

This is a temporary fix. A more permanent one would be to choose a font
supporting all characters used by our polybar configuration. But for
now, this is required so we don't have a bloated journal due to polybar
warnings about unmatched characters.
Adding TODO in #247 to improve the font used.
Closes #308

modules: home: workstation: i3: polybar: disable warning log output

---

.circleci/config.yml
bin/shabka

This allows to do `dotshabka = import <dotshabka> {};` instead of  `dotshabka = import ../.. {};`.
It also allows to do `with <dotshabka/external>;`.

bin/shabka: add dotshabka to NIX_PATH

---

bin/shabka

This allows to execute command like this:
```
DOTSHABKA_PATH=/whatever shabka exec nixos-rebuild switch
DOTSHABKA_PATH=/whatever shabka -h your-host exec nixos-rebuild test
DOTSHABKA_PATH=/whatever shabka exec nixops deploy # not tested
DOTSHABKA_PATH=/whatever shabka exec morph deploy
```

bin/shabka: add exec command
